# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-web-teste

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_518a7f76412445c2aa0e87e735a27116 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a84e27c1cae3482da5479efa3d92c777 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_518a7f76412445c2aa0e87e735a27116 }}/node:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-web-teste'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e9ee743ff87e4c78954b651c37fa1878 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_518a7f76412445c2aa0e87e735a27116 }}/node:${{ github.sha }}'